CREATE TABLE tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status TEXT NOT NULL CHECK (status IN ('open', 'in_progress', 'completed', 'failed', 'blocked', 'closed')),
  assignment_target_type TEXT,
  assignment_target_id BIGINT,
  body JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(body) = 'object'),
  revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE RESTRICT,
  agent_id BIGINT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed', 'interrupted')),
  execution_mode TEXT NOT NULL CHECK (execution_mode IN ('agent', 'workflow')),
  lease_owner TEXT,
  lease_expires_at TIMESTAMPTZ,
  last_heartbeat_at TIMESTAMPTZ,
  body JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(body) = 'object'),
  revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT runs_id_ticket_unique UNIQUE (id, ticket_id),
  CONSTRAINT runs_lease_complete CHECK (
    (lease_owner IS NULL AND lease_expires_at IS NULL) OR
    (lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)
  )
);

CREATE INDEX runs_pending_claim_idx ON runs (created_at, id) WHERE status = 'pending';
CREATE INDEX runs_ticket_idx ON runs (ticket_id, created_at, id);
CREATE INDEX runs_lease_expiry_idx ON runs (lease_expires_at) WHERE lease_owner IS NOT NULL;

CREATE TABLE run_event_chain_tips (
  run_id BIGINT PRIMARY KEY REFERENCES runs(id) ON DELETE RESTRICT,
  next_seq BIGINT NOT NULL DEFAULT 0 CHECK (next_seq >= 0),
  previous_hash TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT run_event_chain_tip_hash CHECK (
    (next_seq = 0 AND previous_hash IS NULL) OR
    (next_seq > 0 AND previous_hash ~ '^[0-9a-f]{64}$')
  )
);

CREATE TABLE events (
  position BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id UUID NOT NULL UNIQUE,
  schema_version INTEGER NOT NULL,
  ts TIMESTAMPTZ NOT NULL,
  type TEXT NOT NULL CHECK (length(btrim(type)) > 0),
  ticket_id BIGINT REFERENCES tickets(id) ON DELETE RESTRICT,
  run_id BIGINT,
  step_id TEXT,
  seq BIGINT,
  prev_hash TEXT,
  hash TEXT,
  payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  CONSTRAINT events_run_ticket_fk FOREIGN KEY (run_id, ticket_id)
    REFERENCES runs(id, ticket_id) ON DELETE RESTRICT,
  CONSTRAINT events_run_seq_unique UNIQUE (run_id, seq),
  CONSTRAINT events_chain_shape CHECK (
    (
      run_id IS NULL AND seq IS NULL AND prev_hash IS NULL AND hash IS NULL
    ) OR (
      run_id IS NOT NULL AND ticket_id IS NOT NULL AND seq >= 0 AND
      hash ~ '^[0-9a-f]{64}$' AND
      (
        (seq = 0 AND prev_hash IS NULL) OR
        (seq > 0 AND prev_hash ~ '^[0-9a-f]{64}$')
      )
    )
  )
);

CREATE INDEX events_ticket_position_idx ON events (ticket_id, position);
CREATE INDEX events_type_position_idx ON events (type, position DESC);

CREATE FUNCTION reject_event_mutation() RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
  RAISE EXCEPTION 'events are append-only';
END;
$function$;

CREATE TRIGGER events_append_only
BEFORE UPDATE OR DELETE ON events
FOR EACH ROW EXECUTE FUNCTION reject_event_mutation();
